### curl -X POST http://localhost:8080/register -d '{"username": "user1", "password": "password"}' -H 'Content-Type: application/json'
GET http://localhost:8080/ping HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/message?name=name1 HTTP/1.1
content-type: application/json

###
POST http://localhost:8080/movie HTTP/1.1
content-type: application/json

{
    "name": "movie1",
    "score": 44
}
