### curl -X POST http://localhost:8080/register -d '{"username": "user1", "password": "password"}' -H 'Content-Type: application/json'
POST http://localhost:8080/register HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "password"
}

###
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "password"
}

###
GET http://localhost:8080/findAll HTTP/1.1
